[env:pico]
platform                    = https://github.com/maxgerhardt/platform-raspberrypi.git
board                       = rpipico
framework                   = arduino
board_build.core            = earlephilhower
board_build.filesystem_size = 0m
monitor_speed               = 115200
lib_deps =
    teemuatlut/TMCStepper
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
